#!/bin/bash

CURRENT_DIR=$(pwd)

LD_LIB_PATH=${CURRENT_DIR}
OPENCV_JAR="BoofCV.jar"
SUFFIX_OPTIONS=":."
COMPILER="java -cp"
COMPILED_FILES="E"

#FULL_RUN_CMD='LD_LIBRARY_PATH="${LD_LIB_PATH}" ${COMPILER} "${CURRENT_DIR}/${OPENCV_JAR}${SUFFIX_OPTIONS}:${CURRENT_DIR}/georegression.jar${SUFFIX_OPTIONS}" ${COMPILED_FILES}'
FULL_RUN_CMD='${COMPILER} "${CURRENT_DIR}/${OPENCV_JAR}${SUFFIX_OPTIONS}:*" ${COMPILED_FILES}'

echo ""
eval echo "[ run.sh ] INFO: Running ${FULL_RUN_CMD}"
echo""

eval ${FULL_RUN_CMD}