#!/bin/bash

CURRENT_DIR=$(pwd)

LD_LIB_PATH=${CURRENT_DIR}
OPENCV_JAR="opencv-340.jar"
SUFFIX_OPTIONS=":."
COMPILER="java -cp "
COMPILED_FILES="Shapes"

FULL_RUN_CMD='LD_LIBRARY_PATH="${LD_LIB_PATH}" ${COMPILER} "${CURRENT_DIR}/${OPENCV_JAR}${SUFFIX_OPTIONS}" ${COMPILED_FILES}'

eval echo "[ run.sh ] INFO: Running ${FULL_RUN_CMD}"

eval ${FULL_RUN_CMD}
